export const data = [
  {
    id: 10,
    first_name: "Manoj",
    last_name: "Gurung",
    email: "manoj.gurung@example.com",
    phone: "9803456789",
    gender: "MALE",
    address: "Pokhara, Kaski",
    dob: "1990-11-12T00:00:00.000Z",
    role: "PATIENTS",
    bloodGroup: "O+",
    balance: 1200,
    insurance_company: {
      company_name: "Reliable Insurance",
    },
  },
  {
    id: 9,
    first_name: "Sagar",
    last_name: "Adhikari",
    email: "sagar.adhikari@example.com",
    phone: "9812345678",
    gender: "MALE",
    address: "Pokhara, Kaski",
    dob: "1990-11-12T00:00:00.000Z",
    role: "PATIENTS",
    bloodGroup: "B+",
    balance: 1200,
    insurance_company: {
      company_name: "Reliable Insurance",
    },
  },
  {
    id: 11,
    first_name: "Rekha",
    last_name: "Magar",
    email: "rekha.magar@example.com",
    phone: "9812345678",
    gender: "FEMALE",
    address: "Jhapa, Damak",
    dob: "1996-08-05T00:00:00.000Z",
    role: "INSURANCE",
    bloodGroup: "A+",
    balance: 1000,
    insurance_company: {
      company_name: "Nepal Insurance Co.",
    },
  },
  {
    id: 12,
    first_name: "Rajesh",
    last_name: "Lama",
    email: "rajesh.lama@example.com",
    phone: "9841239876",
    gender: "MALE",
    address: "Hetauda, Makwanpur",
    dob: "1985-04-20T00:00:00.000Z",
    role: "HOSPITAL",
    bloodGroup: "B+",
    balance: 500,
    insurance_company: {
      company_name: "Himalayan General Insurance",
    },
  },
  {
    id: 13,
    first_name: "Aarati",
    last_name: "Rai",
    email: "aarati.rai@example.com",
    phone: "9801122233",
    gender: "FEMALE",
    address: "Birgunj, Parsa",
    dob: "1994-12-25T00:00:00.000Z",
    role: "PATIENTS",
    bloodGroup: "A-",
    balance: 800,
    insurance_company: {
      company_name: "Himalayan General Insurance",
    },
  },
  {
    id: 14,
    first_name: "Nabin",
    last_name: "Shahi",
    email: "nabin.shahi@example.com",
    phone: "9845671234",
    gender: "MALE",
    address: "Surkhet, Birendranagar",
    dob: "1989-03-14T00:00:00.000Z",
    role: "INSURANCE",
    bloodGroup: "O+",
    balance: 1100,
    insurance_company: {
      company_name: "Shikhar Insurance",
    },
  },
  {
    id: 15,
    first_name: "Sarita",
    last_name: "Karki",
    email: "sarita.karki@hospital.com",
    phone: "9823456789",
    gender: "FEMALE",
    address: "Nepalgunj, Banke",
    dob: "1982-07-09T00:00:00.000Z",
    role: "HOSPITAL",
    bloodGroup: "B-",
    balance: 2000,
    insurance_company: {
      company_name: "Asian Life Insurance",
    },
  },
  {
    id: 16,
    first_name: "Kamal",
    last_name: "Poudel",
    email: "kamal.poudel@example.com",
    phone: "9812233445",
    gender: "MALE",
    address: "Butwal, Rupandehi",
    dob: "1992-02-18T00:00:00.000Z",
    role: "PATIENTS",
    bloodGroup: "B+",
    balance: 1000,
    insurance_company: {
      company_name: "LifeCare Insurance",
    },
  },
  {
    id: 17,
    first_name: "Mina",
    last_name: "Tamang",
    email: "mina.tamang@insurance.com",
    phone: "9809876543",
    gender: "FEMALE",
    address: "Dharan, Sunsari",
    dob: "1997-09-19T00:00:00.000Z",
    role: "INSURANCE",
    bloodGroup: "A-",
    balance: 1300,
    insurance_company: {
      company_name: "Prime Insurance Co.",
    },
  },
  {
    id: 18,
    first_name: "Bikash",
    last_name: "Bista",
    email: "bikash.bista@hospital.com",
    phone: "9848765432",
    gender: "MALE",
    address: "Dhangadhi, Kailali",
    dob: "1990-10-10T00:00:00.000Z",
    role: "HOSPITAL",
    bloodGroup: "O+",
    balance: 1400,
    insurance_company: {
      company_name: "Reliable Insurance",
    },
  },
];
